/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.huawei.mrs.flink.pojo;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6029757732569298950L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Address\",\"namespace\":\"com.huawei.mrs.flink.pojo\",\"fields\":[{\"name\":\"city\",\"type\":[\"null\",\"string\"]},{\"name\":\"district\",\"type\":[\"null\",\"string\"]},{\"name\":\"houseNum\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Address> ENCODER =
      new BinaryMessageEncoder<Address>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Address> DECODER =
      new BinaryMessageDecoder<Address>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Address>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Address to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Address from a ByteBuffer. */
  public static Address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence city;
  @Deprecated public java.lang.CharSequence district;
  @Deprecated public java.lang.Integer houseNum;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Address() {}

  /**
   * All-args constructor.
   * @param city The new value for city
   * @param district The new value for district
   * @param houseNum The new value for houseNum
   */
  public Address(java.lang.CharSequence city, java.lang.CharSequence district, java.lang.Integer houseNum) {
    this.city = city;
    this.district = district;
    this.houseNum = houseNum;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return city;
    case 1: return district;
    case 2: return houseNum;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: city = (java.lang.CharSequence)value$; break;
    case 1: district = (java.lang.CharSequence)value$; break;
    case 2: houseNum = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'district' field.
   * @return The value of the 'district' field.
   */
  public java.lang.CharSequence getDistrict() {
    return district;
  }

  /**
   * Sets the value of the 'district' field.
   * @param value the value to set.
   */
  public void setDistrict(java.lang.CharSequence value) {
    this.district = value;
  }

  /**
   * Gets the value of the 'houseNum' field.
   * @return The value of the 'houseNum' field.
   */
  public java.lang.Integer getHouseNum() {
    return houseNum;
  }

  /**
   * Sets the value of the 'houseNum' field.
   * @param value the value to set.
   */
  public void setHouseNum(java.lang.Integer value) {
    this.houseNum = value;
  }

  /**
   * Creates a new Address RecordBuilder.
   * @return A new Address RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.Address.Builder newBuilder() {
    return new com.huawei.mrs.flink.pojo.Address.Builder();
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Address RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.Address.Builder newBuilder(com.huawei.mrs.flink.pojo.Address.Builder other) {
    return new com.huawei.mrs.flink.pojo.Address.Builder(other);
  }

  /**
   * Creates a new Address RecordBuilder by copying an existing Address instance.
   * @param other The existing instance to copy.
   * @return A new Address RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.Address.Builder newBuilder(com.huawei.mrs.flink.pojo.Address other) {
    return new com.huawei.mrs.flink.pojo.Address.Builder(other);
  }

  /**
   * RecordBuilder for Address instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Address>
    implements org.apache.avro.data.RecordBuilder<Address> {

    private java.lang.CharSequence city;
    private java.lang.CharSequence district;
    private java.lang.Integer houseNum;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.huawei.mrs.flink.pojo.Address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.district)) {
        this.district = data().deepCopy(fields()[1].schema(), other.district);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.houseNum)) {
        this.houseNum = data().deepCopy(fields()[2].schema(), other.houseNum);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Address instance
     * @param other The existing instance to copy.
     */
    private Builder(com.huawei.mrs.flink.pojo.Address other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.city)) {
        this.city = data().deepCopy(fields()[0].schema(), other.city);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.district)) {
        this.district = data().deepCopy(fields()[1].schema(), other.district);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.houseNum)) {
        this.houseNum = data().deepCopy(fields()[2].schema(), other.houseNum);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.city = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder clearCity() {
      city = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'district' field.
      * @return The value.
      */
    public java.lang.CharSequence getDistrict() {
      return district;
    }

    /**
      * Sets the value of the 'district' field.
      * @param value The value of 'district'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder setDistrict(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.district = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'district' field has been set.
      * @return True if the 'district' field has been set, false otherwise.
      */
    public boolean hasDistrict() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'district' field.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder clearDistrict() {
      district = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'houseNum' field.
      * @return The value.
      */
    public java.lang.Integer getHouseNum() {
      return houseNum;
    }

    /**
      * Sets the value of the 'houseNum' field.
      * @param value The value of 'houseNum'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder setHouseNum(java.lang.Integer value) {
      validate(fields()[2], value);
      this.houseNum = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'houseNum' field has been set.
      * @return True if the 'houseNum' field has been set, false otherwise.
      */
    public boolean hasHouseNum() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'houseNum' field.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.Address.Builder clearHouseNum() {
      houseNum = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Address build() {
      try {
        Address record = new Address();
        record.city = fieldSetFlags()[0] ? this.city : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.district = fieldSetFlags()[1] ? this.district : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.houseNum = fieldSetFlags()[2] ? this.houseNum : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Address>
    WRITER$ = (org.apache.avro.io.DatumWriter<Address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Address>
    READER$ = (org.apache.avro.io.DatumReader<Address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
