/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.huawei.mrs.flink.pojo;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4629732698747995143L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroData\",\"namespace\":\"com.huawei.mrs.flink.pojo\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"doc\":\"\",\"default\":null},{\"name\":\"age\",\"type\":[\"null\",\"int\"],\"doc\":\"\",\"default\":null},{\"name\":\"address\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Address\",\"fields\":[{\"name\":\"city\",\"type\":[\"null\",\"string\"]},{\"name\":\"district\",\"type\":[\"null\",\"string\"]},{\"name\":\"houseNum\",\"type\":[\"null\",\"int\"]}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroData> ENCODER =
      new BinaryMessageEncoder<AvroData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroData> DECODER =
      new BinaryMessageDecoder<AvroData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroData from a ByteBuffer. */
  public static AvroData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /**  */
  @Deprecated public java.lang.CharSequence name;
  /**  */
  @Deprecated public java.lang.Integer age;
  @Deprecated public com.huawei.mrs.flink.pojo.Address address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroData() {}

  /**
   * All-args constructor.
   * @param name 
   * @param age 
   * @param address The new value for address
   */
  public AvroData(java.lang.CharSequence name, java.lang.Integer age, com.huawei.mrs.flink.pojo.Address address) {
    this.name = name;
    this.age = age;
    this.address = address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return age;
    case 2: return address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: age = (java.lang.Integer)value$; break;
    case 2: address = (com.huawei.mrs.flink.pojo.Address)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return 
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * 
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return 
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * 
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public com.huawei.mrs.flink.pojo.Address getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(com.huawei.mrs.flink.pojo.Address value) {
    this.address = value;
  }

  /**
   * Creates a new AvroData RecordBuilder.
   * @return A new AvroData RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.AvroData.Builder newBuilder() {
    return new com.huawei.mrs.flink.pojo.AvroData.Builder();
  }

  /**
   * Creates a new AvroData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroData RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.AvroData.Builder newBuilder(com.huawei.mrs.flink.pojo.AvroData.Builder other) {
    return new com.huawei.mrs.flink.pojo.AvroData.Builder(other);
  }

  /**
   * Creates a new AvroData RecordBuilder by copying an existing AvroData instance.
   * @param other The existing instance to copy.
   * @return A new AvroData RecordBuilder
   */
  public static com.huawei.mrs.flink.pojo.AvroData.Builder newBuilder(com.huawei.mrs.flink.pojo.AvroData other) {
    return new com.huawei.mrs.flink.pojo.AvroData.Builder(other);
  }

  /**
   * RecordBuilder for AvroData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroData>
    implements org.apache.avro.data.RecordBuilder<AvroData> {

    /**  */
    private java.lang.CharSequence name;
    /**  */
    private java.lang.Integer age;
    private com.huawei.mrs.flink.pojo.Address address;
    private com.huawei.mrs.flink.pojo.Address.Builder addressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.huawei.mrs.flink.pojo.AvroData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.address)) {
        this.address = data().deepCopy(fields()[2].schema(), other.address);
        fieldSetFlags()[2] = true;
      }
      if (other.hasAddressBuilder()) {
        this.addressBuilder = com.huawei.mrs.flink.pojo.Address.newBuilder(other.getAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing AvroData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.huawei.mrs.flink.pojo.AvroData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.age)) {
        this.age = data().deepCopy(fields()[1].schema(), other.age);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.address)) {
        this.address = data().deepCopy(fields()[2].schema(), other.address);
        fieldSetFlags()[2] = true;
      }
      this.addressBuilder = null;
    }

    /**
      * Gets the value of the 'name' field.
      * 
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * 
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * 
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * 
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * 
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * 
      * @param value The value of 'age'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder setAge(java.lang.Integer value) {
      validate(fields()[1], value);
      this.age = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * 
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'age' field.
      * 
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder clearAge() {
      age = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public com.huawei.mrs.flink.pojo.Address getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder setAddress(com.huawei.mrs.flink.pojo.Address value) {
      validate(fields()[2], value);
      this.addressBuilder = null;
      this.address = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'address' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.huawei.mrs.flink.pojo.Address.Builder getAddressBuilder() {
      if (addressBuilder == null) {
        if (hasAddress()) {
          setAddressBuilder(com.huawei.mrs.flink.pojo.Address.newBuilder(address));
        } else {
          setAddressBuilder(com.huawei.mrs.flink.pojo.Address.newBuilder());
        }
      }
      return addressBuilder;
    }

    /**
     * Sets the Builder instance for the 'address' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.huawei.mrs.flink.pojo.AvroData.Builder setAddressBuilder(com.huawei.mrs.flink.pojo.Address.Builder value) {
      clearAddress();
      addressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'address' field has an active Builder instance
     * @return True if the 'address' field has an active Builder instance
     */
    public boolean hasAddressBuilder() {
      return addressBuilder != null;
    }

    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public com.huawei.mrs.flink.pojo.AvroData.Builder clearAddress() {
      address = null;
      addressBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroData build() {
      try {
        AvroData record = new AvroData();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.age = fieldSetFlags()[1] ? this.age : (java.lang.Integer) defaultValue(fields()[1]);
        if (addressBuilder != null) {
          record.address = this.addressBuilder.build();
        } else {
          record.address = fieldSetFlags()[2] ? this.address : (com.huawei.mrs.flink.pojo.Address) defaultValue(fields()[2]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroData>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroData>
    READER$ = (org.apache.avro.io.DatumReader<AvroData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
