analyze  call_center;
analyze  catalog_page;
analyze  catalog_returns;
analyze  catalog_sales;
analyze  customer_address;
analyze  customer_demographics ;
analyze  customer ;
analyze  date_dim ;
analyze  household_demographics ;
analyze  income_band ;
analyze  inventory ;
analyze  item ;
analyze  promotion ;
analyze  reason ;
analyze  ship_mode ;
analyze  store_returns ;
analyze  store_sales ;
analyze  store ;
analyze  time_dim ;
analyze  warehouse ;
analyze  web_page ;
analyze  web_returns ;
analyze  web_sales ;
analyze  web_site ;
