iotdb_ssl_enable=true
jdbc_url=jdbc:iotdb://127.0.0.1:22260/
username=xxxxxx
# IoTDB 用户密码，建议密文存放，使用时解密，确保安全。
password=xxxxxx
# 下载的认证凭据中“krb5.conf”文件的位置，linux环境下建议使用客户端安装conf目录下的krb5.conf文件，Windows环境下使用“\\”，填写文件绝对路径
krb5_conf_dest=/opt/client/IoTDB/iotdb/conf/krb5.conf
# 下载的认证凭据中“user.keytab”文件的位置，linux环境下建议使用客户端安装conf目录下的user.keytab文件，Windows环境下使用“\\”，填写文件绝对路径
key_tab_dest=/opt/client/IoTDB/iotdb/conf/user.keytab
# 对应user.keytab的用户名@HADOOP.COM
client_principal=xxxxxx@HADOOP.COM
# truststore文件路径，linux环境下建议使用客户端安装conf目录下的truststore文件，Windows环境下使用“\\”，填写文件绝对路径
iotdb_ssl_truststore=/opt/client/IoTDB/iotdb/conf/truststore.jks