iotdb_ssl_enable=true
# host
local_host=127.0.0.1
# port
local_port=22260
# IoTDB 用户名
username=xxxxxx
# IoTDB 用户密码，建议密文存放，使用时解密，确保安全。
password=xxxxxx
# truststore文件路径，Windows环境下使用“\\”，填写文件绝对路径
iotdb_ssl_truststore=D:\\iotdb-kafka-example\\src\\main\\resources\\truststore.jks
# 用户自己申请的机机账号keytab文件名称
user_keytab_file=user.keytab
# 用户自己申请的机机账号名称
user_principal=xxxxxx
# Kafka bootstrap.server
bootstrap_server_url=127.0.0.1:21007