/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.huawei.hwclouds.drs.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Date extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5099846483595947937L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Date\",\"namespace\":\"com.huawei.hwclouds.drs.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\",\"doc\":\"Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Date> ENCODER =
      new BinaryMessageEncoder<Date>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Date> DECODER =
      new BinaryMessageDecoder<Date>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Date> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Date> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Date>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Date to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Date from a ByteBuffer. */
  public static Date fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS */
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Date() {}

  /**
   * All-args constructor.
   * @param value Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
   */
  public Date(java.lang.CharSequence value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   * @return Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new Date RecordBuilder.
   * @return A new Date RecordBuilder
   */
  public static com.huawei.hwclouds.drs.avro.Date.Builder newBuilder() {
    return new com.huawei.hwclouds.drs.avro.Date.Builder();
  }

  /**
   * Creates a new Date RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Date RecordBuilder
   */
  public static com.huawei.hwclouds.drs.avro.Date.Builder newBuilder(com.huawei.hwclouds.drs.avro.Date.Builder other) {
    return new com.huawei.hwclouds.drs.avro.Date.Builder(other);
  }

  /**
   * Creates a new Date RecordBuilder by copying an existing Date instance.
   * @param other The existing instance to copy.
   * @return A new Date RecordBuilder
   */
  public static com.huawei.hwclouds.drs.avro.Date.Builder newBuilder(com.huawei.hwclouds.drs.avro.Date other) {
    return new com.huawei.hwclouds.drs.avro.Date.Builder(other);
  }

  /**
   * RecordBuilder for Date instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Date>
    implements org.apache.avro.data.RecordBuilder<Date> {

    /** Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS */
    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.huawei.hwclouds.drs.avro.Date.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Date instance
     * @param other The existing instance to copy.
     */
    private Builder(com.huawei.hwclouds.drs.avro.Date other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'value' field.
      * Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.huawei.hwclouds.drs.avro.Date.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'value' field.
      * Field.dataTypeNumber = 94(DateTime) format:YYYY-MM-DD HH:MM:SS
      * @return This builder.
      */
    public com.huawei.hwclouds.drs.avro.Date.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Date build() {
      try {
        Date record = new Date();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Date>
    WRITER$ = (org.apache.avro.io.DatumWriter<Date>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Date>
    READER$ = (org.apache.avro.io.DatumReader<Date>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
