iotdb_ssl_enable=true
local_host=127.0.0.1
local_port=22260
username=xxxxxx
# IoTDB 用户密码，建议密文存放，使用时解密，确保安全。
password=xxxxxx
# truststore文件路径，linux环境下建议使用客户端安装conf目录下的truststore文件
iotdb_ssl_truststore=/opt/client/IoTDB/iotdb/conf/truststore.jks