<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.huawei.mrs</groupId>
    <artifactId>hetu-examples-security</artifactId>
    <version>8.6.0-360.r9</version>

    <properties>
        <source>1.8</source>
        <target>1.8</target>
        <dep.slf4j.version>2.0.16</dep.slf4j.version>
        <dep.reload4j.version>1.2.26</dep.reload4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.trino</groupId>
            <artifactId>hetu-jdbc</artifactId>
            <version>453-h0.cbu.mrs.360.r9</version>
            <exclusions>
                <exclusion>
                    <artifactId>*</artifactId>
                    <groupId>*</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${dep.slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-reload4j</artifactId>
            <version>${dep.slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.reload4j</groupId>
            <artifactId>reload4j</artifactId>
            <version>${dep.reload4j.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>build-with-jdk8</id>
            <activation>
                <jdk>[1.8,17)</jdk>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <source>1.8</source>
                <target>1.8</target>
            </properties>
        </profile>
        <profile>
            <id>build-with-jdk17</id>
            <activation>
                <jdk>[17,21)</jdk>
            </activation>
            <properties>
                <source>17</source>
                <target>17</target>
            </properties>
        </profile>
        <profile>
            <id>build-with-jdk21</id>
            <activation>
                <jdk>[21,)</jdk>
            </activation>
            <properties>
                <source>21</source>
                <target>21</target>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>${source}</source>
                    <target>${target}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifest>
                            <mainClass>com.huawei.hetu.JDBCExampleBroker</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>